# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Student.create(name: 'SusieQ', grade: 10, username: "susieQ", password: "1234")
Student.create(name: 'Emma', grade: 10, username: "ejg", password: "arch")
Student.create(name: 'Jenny', grade: 10, username: "jaguar", password: "arch")
Student.create(name: 'Caroline', grade: 10, username: "carol", password: "arch")
Student.create(name: 'Ali', grade: 10, username: "aliG", password: "paint")
Student.create(name: 'Jack', grade: 10, username: "jack", password: "123")
Student.create(name: 'Clark', grade: 10, username: "clark", password: "123")
Student.create(name: 'Ethan', grade: 10, username: "ejh", password: "deng")

Assignment.create(details: "pp 43-45: #1,2, 5-10", course_id:1)
Assignment.create(details: "Read pp 122-139", course_id: 2)
Assignment.create(details: "Section 4.1 #2, 4, 7-19odd, 23", course_id: 1)

Teacher.create(name: "Britney", username: "BritV", password: "123")
Teacher.create(name: "Clarion", username: "clh", password: "asdf")
Teacher.create(name: "Peregrine", username: "pth", password: "pgrin")


Course.create(title: "Geometry", teacher_id: 1)
Course.create(title: "BC Calculus", teacher_id: 2)
Course.create(title: "Chinese", teacher_id: 3)
Course.create(title: "Advanced Trig", teacher_id: 1)
Course.create(title: "Constitutional Law", teacher_id: 2)
Course.create(title: "US History", teacher_id: 3)
Course.create(title: "Algebra II", teacher_id: 2)
Course.create(title: "Literary Fantasy", teacher_id: 2)
Course.create(title: "Shakespeare", teacher_id: 3)
Course.create(title: "Psychology", teacher_id: 3)


CoursesStudent.create(student_id: 1, course_id: 1)
CoursesStudent.create(student_id: 1, course_id: 3)
CoursesStudent.create(student_id: 1, course_id: 5)
CoursesStudent.create(student_id: 1, course_id: 8)
CoursesStudent.create(student_id: 2, course_id: 2)
CoursesStudent.create(student_id: 2, course_id: 3)
CoursesStudent.create(student_id: 2, course_id: 4)
CoursesStudent.create(student_id: 2, course_id: 5)
CoursesStudent.create(student_id: 2, course_id: 8)
CoursesStudent.create(student_id: 3, course_id: 1)
CoursesStudent.create(student_id: 3, course_id: 6)
CoursesStudent.create(student_id: 3, course_id: 8)
CoursesStudent.create(student_id: 3, course_id: 9)
CoursesStudent.create(student_id: 3, course_id: 10)
CoursesStudent.create(student_id: 4, course_id: 2)
CoursesStudent.create(student_id: 4, course_id: 6)
CoursesStudent.create(student_id: 4, course_id: 7)
CoursesStudent.create(student_id: 4, course_id: 8)
CoursesStudent.create(student_id: 4, course_id: 9)
CoursesStudent.create(student_id: 5, course_id: 3)
CoursesStudent.create(student_id: 5, course_id: 4)
CoursesStudent.create(student_id: 5, course_id: 5)
CoursesStudent.create(student_id: 5, course_id: 10)
CoursesStudent.create(student_id: 5, course_id: 7)
CoursesStudent.create(student_id: 6, course_id: 2)
CoursesStudent.create(student_id: 6, course_id: 3)
CoursesStudent.create(student_id: 6, course_id: 4)
CoursesStudent.create(student_id: 6, course_id: 5)
CoursesStudent.create(student_id: 6, course_id: 6)
CoursesStudent.create(student_id: 7, course_id: 1)
CoursesStudent.create(student_id: 7, course_id: 4)
CoursesStudent.create(student_id: 7, course_id: 7)
CoursesStudent.create(student_id: 7, course_id: 9)
CoursesStudent.create(student_id: 7, course_id: 10)
CoursesStudent.create(student_id: 8, course_id: 2)
CoursesStudent.create(student_id: 8, course_id: 5)
CoursesStudent.create(student_id: 8, course_id: 7)
CoursesStudent.create(student_id: 8, course_id: 8)


Response.create(answer: 'yellow', datatype:'light', day: "0428.1510", courses_student_id: 1, course_id: 1, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0427.1910", courses_student_id: 1, course_id: 1, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0426.1010", courses_student_id: 1, course_id: 1, student_id: 1)
Response.create(answer: 'yellow', datatype:'light', day: "0425.0810", courses_student_id: 1, course_id: 1, student_id: 1)
Response.create(answer: 'red', datatype:'light', day: "0424.0910", courses_student_id: 1, course_id: 1, student_id: 1)
Response.create(answer: 'red', datatype:'light', day: "0423.1210", courses_student_id: 1, course_id: 1, student_id: 1)
Response.create(answer: 'red', datatype:'light', day: "0422.1010", courses_student_id: 1, course_id: 1, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0427.1833", courses_student_id: 2, course_id: 3, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0426.0333", courses_student_id: 2, course_id: 3, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0425.0933", courses_student_id: 2, course_id: 3, student_id: 1)
Response.create(answer: 'yellow', datatype:'light', day: "0424.1133", courses_student_id: 2, course_id: 3, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0423.0633", courses_student_id: 2, course_id: 3, student_id: 1)
Response.create(answer: 'yellow', datatype:'light', day: "0428.1033", courses_student_id: 2, course_id: 3, student_id: 1)
Response.create(answer: 'yellow', datatype:'light', day: "0422.0833", courses_student_id: 2, course_id: 3, student_id: 1)
Response.create(answer: 'red', datatype:'light', day: "0428.0833", courses_student_id: 3, course_id: 5, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0427.133", courses_student_id: 3, course_id: 5, student_id: 1)
Response.create(answer: 'yellow', datatype:'light', day: "0426.0833", courses_student_id: 3, course_id: 5, student_id: 1)
Response.create(answer: 'yellow', datatype:'light', day: "0425.0833", courses_student_id: 3, course_id: 5, student_id: 1)
Response.create(answer: 'red', datatype:'light', day: "0424.0833", courses_student_id: 3, course_id: 5, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0423.0833", courses_student_id: 3, course_id: 5, student_id: 1)
Response.create(answer: 'red', datatype:'light', day: "0422.0833", courses_student_id: 3, course_id: 5, student_id: 1)
Response.create(answer: 'yellow', datatype:'light', day: "0428.0833", courses_student_id: 3, course_id: 5, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0428.0833", courses_student_id: 4, course_id: 8, student_id: 1)
Response.create(answer: 'yellow', datatype:'light', day: "0427.1233", courses_student_id: 4, course_id: 8, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0426.0833", courses_student_id: 4, course_id: 8, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0425.0333", courses_student_id: 4, course_id: 8, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0424.0533", courses_student_id: 4, course_id: 8, student_id: 1)
Response.create(answer: 'red', datatype:'light', day: "0423.1733", courses_student_id: 4, course_id: 8, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0422.2033", courses_student_id: 4, course_id: 8, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0421.2133", courses_student_id: 4, course_id: 8, student_id: 1)
Response.create(answer: 'green', datatype:'light', day: "0428.2133", courses_student_id: 5, course_id: 2, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0427.0933", courses_student_id: 5, course_id: 2, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0426.0833", courses_student_id: 5, course_id: 2, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0425.1133", courses_student_id: 5, course_id: 2, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0424.0833", courses_student_id: 5, course_id: 2, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0423.2333", courses_student_id: 5, course_id: 2, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0422.2133", courses_student_id: 5, course_id: 2, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0428.2133", courses_student_id: 6, course_id: 3, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0427.2133", courses_student_id: 6, course_id: 3, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0426.2133", courses_student_id: 6, course_id: 3, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0425.2133", courses_student_id: 6, course_id: 3, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0424.2133", courses_student_id: 6, course_id: 3, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0423.2133", courses_student_id: 6, course_id: 3, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0422.2133", courses_student_id: 6, course_id: 3, student_id: 2)
Response.create(answer: 'red', datatype:'light', day: "0422.2133", courses_student_id: 7, course_id: 4, student_id: 2)
Response.create(answer: 'red', datatype:'light', day: "0423.2133", courses_student_id: 7, course_id: 4, student_id: 2)
Response.create(answer: 'red', datatype:'light', day: "0424.2133", courses_student_id: 7, course_id: 4, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0425.2133", courses_student_id: 7, course_id: 4, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0426.2133", courses_student_id: 7, course_id: 4, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0427.2133", courses_student_id: 7, course_id: 4, student_id: 2)
Response.create(answer: 'red', datatype:'light', day: "0428.2133", courses_student_id: 7, course_id: 4, student_id: 2)
Response.create(answer: 'red', datatype:'light', day: "0421.2133", courses_student_id: 7, course_id: 4, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0422.2133", courses_student_id: 8, course_id: 5, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0423.2133", courses_student_id: 8, course_id: 5, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0424.2033", courses_student_id: 8, course_id: 5, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0425.1233", courses_student_id: 8, course_id: 5, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0426.0533", courses_student_id: 8, course_id: 5, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0427.0933", courses_student_id: 8, course_id: 5, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0428.2033", courses_student_id: 8, course_id: 5, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0422.2133", courses_student_id: 9, course_id: 8, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0423.2133", courses_student_id: 9, course_id: 8, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0424.2133", courses_student_id: 9, course_id: 8, student_id: 2)
Response.create(answer: 'yellow', datatype:'light', day: "0425.2133", courses_student_id: 9, course_id: 8, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0426.2133", courses_student_id: 9, course_id: 8, student_id: 2)
Response.create(answer: 'red', datatype:'light', day: "0427.2133", courses_student_id: 9, course_id: 8, student_id: 2)
Response.create(answer: 'green', datatype:'light', day: "0421.1105", courses_student_id: 10, course_id: 1, student_id: 3)
Response.create(answer: 'yellow', datatype:'light', day: "0422.1133", courses_student_id: 10, course_id: 1, student_id: 3)
Response.create(answer: 'green', datatype:'light', day: "0423.0933", courses_student_id: 10, course_id: 1, student_id: 3)
Response.create(answer: 'yellow', datatype:'light', day: "0424.1105", courses_student_id: 10, course_id: 1, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0425.2133", courses_student_id: 10, course_id: 1, student_id: 3)
Response.create(answer: 'yellow', datatype:'light', day: "0426.2133", courses_student_id: 10, course_id: 1, student_id: 3)
Response.create(answer: 'green', datatype:'light', day: "0427.2133", courses_student_id: 10, course_id: 1, student_id: 3)
Response.create(answer: 'green', datatype:'light', day: "0428.2133", courses_student_id: 11, course_id: 6, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0427.2133", courses_student_id: 11, course_id: 6, student_id: 3)
Response.create(answer: 'yellow', datatype:'light', day: "0426.2133", courses_student_id: 11, course_id: 6, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0425.2133", courses_student_id: 11, course_id: 6, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0424.2133", courses_student_id: 11, course_id: 6, student_id: 3)
Response.create(answer: 'yellow', datatype:'light', day: "0423.1640", courses_student_id: 11, course_id: 6, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0422.1640", courses_student_id: 12, course_id: 8, student_id: 3)
Response.create(answer: 'green', datatype:'light', day: "0423.1640", courses_student_id: 12, course_id: 8, student_id: 3)
Response.create(answer: 'green', datatype:'light', day: "0424.1640", courses_student_id: 12, course_id: 8, student_id: 3)
Response.create(answer: 'yellow', datatype:'light', day: "0425.1640", courses_student_id: 12, course_id: 8, student_id: 3)
Response.create(answer: 'green', datatype:'light', day: "0426.1640", courses_student_id: 12, course_id: 8, student_id: 3)
Response.create(answer: 'green', datatype:'light', day: "0427.1640", courses_student_id: 12, course_id: 8, student_id: 3)
Response.create(answer: 'yellow', datatype:'light', day: "0428.1640", courses_student_id: 12, course_id: 8, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0429.1640", courses_student_id: 12, course_id: 8, student_id: 3)
Response.create(answer: 'yellow', datatype:'light', day: "0428.1640", courses_student_id: 13, course_id: 9, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0427.1640", courses_student_id: 13, course_id: 9, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0426.1640", courses_student_id: 13, course_id: 9, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0425.1640", courses_student_id: 13, course_id: 9, student_id: 3)
Response.create(answer: 'yellow', datatype:'light', day: "0424.1640", courses_student_id: 13, course_id: 9, student_id: 3)
Response.create(answer: 'green', datatype:'light', day: "0423.1640", courses_student_id: 13, course_id: 9, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0422.1640", courses_student_id: 13, course_id: 9, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0428.1640", courses_student_id: 14, course_id: 10, student_id: 3)
Response.create(answer: 'red', datatype:'light', day: "0427.2140", courses_student_id: 22, course_id: 5, student_id: 5)
Response.create(answer: 'green', datatype:'light', day: "0426.1040", courses_student_id: 22, course_id: 5, student_id: 5)
Response.create(answer: 'green', datatype:'light', day: "0425.1640", courses_student_id: 22, course_id: 5, student_id: 5)
Response.create(answer: 'yellow', datatype:'light', day: "0424.1640", courses_student_id: 22, course_id: 5, student_id: 5)
Response.create(answer: 'green', datatype:'light', day: "0423.0940", courses_student_id: 22, course_id: 5, student_id: 5)
Response.create(answer: 'green', datatype:'light', day: "0422.1740", courses_student_id: 22, course_id: 5, student_id: 5)
Response.create(answer: 'green', datatype:'light', day: "0428.1640", courses_student_id: 22, course_id: 5, student_id: 5)


